-- ============================================================================
-- CfgS_Upgrades (server)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: Upgrades.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgS_Upgrades = {}

CfgS_Upgrades.dCfgUpgrade = {}
CfgS_Upgrades.allCfgUpgrades = {
    "speed",
    "carry",
    "atk",
    "atkspd",
    "range",
    "gold",
    "spawn",
    "ore_luck",
    "slow",
    "repair",
    "armor",
    "multi",
    "turret_arrow",
    "turret_minigun",
    "turret_flame",
    "turret_sniper",
    "turret_electric",
    "turret_rocket",
}
local _createCfgUpgrade = {
    ["speed"] = function()
        return {
            Id = "speed",
            IsTurret = false,
        }
    end,
    ["carry"] = function()
        return {
            Id = "carry",
            IsTurret = false,
        }
    end,
    ["atk"] = function()
        return {
            Id = "atk",
            IsTurret = false,
        }
    end,
    ["atkspd"] = function()
        return {
            Id = "atkspd",
            IsTurret = false,
        }
    end,
    ["range"] = function()
        return {
            Id = "range",
            IsTurret = false,
        }
    end,
    ["gold"] = function()
        return {
            Id = "gold",
            IsTurret = false,
        }
    end,
    ["spawn"] = function()
        return {
            Id = "spawn",
            IsTurret = false,
        }
    end,
    ["ore_luck"] = function()
        return {
            Id = "ore_luck",
            IsTurret = false,
        }
    end,
    ["slow"] = function()
        return {
            Id = "slow",
            IsTurret = false,
        }
    end,
    ["repair"] = function()
        return {
            Id = "repair",
            IsTurret = false,
        }
    end,
    ["armor"] = function()
        return {
            Id = "armor",
            IsTurret = false,
        }
    end,
    ["multi"] = function()
        return {
            Id = "multi",
            IsTurret = false,
        }
    end,
    ["turret_arrow"] = function()
        return {
            Id = "turret_arrow",
            IsTurret = true,
            TurretType = "arrow",
        }
    end,
    ["turret_minigun"] = function()
        return {
            Id = "turret_minigun",
            IsTurret = true,
            TurretType = "minigun",
        }
    end,
    ["turret_flame"] = function()
        return {
            Id = "turret_flame",
            IsTurret = true,
            TurretType = "flame",
        }
    end,
    ["turret_sniper"] = function()
        return {
            Id = "turret_sniper",
            IsTurret = true,
            TurretType = "sniper",
        }
    end,
    ["turret_electric"] = function()
        return {
            Id = "turret_electric",
            IsTurret = true,
            TurretType = "electric",
        }
    end,
    ["turret_rocket"] = function()
        return {
            Id = "turret_rocket",
            IsTurret = true,
            TurretType = "rocket",
        }
    end,
}

function CfgS_Upgrades.Get_dCfgUpgrade(id)
    local data = CfgS_Upgrades.dCfgUpgrade[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgUpgrade[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_Upgrades.dCfgUpgrade[id] = data
    return data
end

function CfgS_Upgrades.Get_CfgUpgradeByIndex(index)
    if index < 0 or index >= #CfgS_Upgrades.allCfgUpgrades then
        return nil
    end
    return CfgS_Upgrades.Get_dCfgUpgrade(CfgS_Upgrades.allCfgUpgrades[index + 1])
end

return CfgS_Upgrades
