-- ============================================================================
-- CfgS_Upgrades (server)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: Upgrades.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgS_Upgrades = {}

CfgS_Upgrades.dCfgUpgrade = {}
CfgS_Upgrades.allCfgUpgrades = {
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
}
local _createCfgUpgrade = {
    [1] = function()
        return {
            Id = 1,
            Key = "speed",
            Name = "急行军",
            Desc = "移动速度+25%",
            Icon = "boot",
            IsTurret = false,
        }
    end,
    [2] = function()
        return {
            Id = 2,
            Key = "carry",
            Name = "军用背包",
            Desc = "携带上限+5",
            Icon = "bag",
            IsTurret = false,
        }
    end,
    [3] = function()
        return {
            Id = 3,
            Key = "atk",
            Name = "利刃强化",
            Desc = "攻击力+1",
            Icon = "sword",
            IsTurret = false,
        }
    end,
    [4] = function()
        return {
            Id = 4,
            Key = "atkspd",
            Name = "疾风斩",
            Desc = "攻击速度+30%",
            Icon = "wind",
            IsTurret = false,
        }
    end,
    [5] = function()
        return {
            Id = 5,
            Key = "range",
            Name = "长臂猿",
            Desc = "攻击范围+35%",
            Icon = "magnet",
            IsTurret = false,
        }
    end,
    [6] = function()
        return {
            Id = 6,
            Key = "gold",
            Name = "物资交换",
            Desc = "提交金币+50%",
            Icon = "coin",
            IsTurret = false,
        }
    end,
    [7] = function()
        return {
            Id = 7,
            Key = "spawn",
            Name = "丰收区域",
            Desc = "资源生成+30%",
            Icon = "star",
            IsTurret = false,
        }
    end,
    [8] = function()
        return {
            Id = 8,
            Key = "ore_luck",
            Name = "探矿直觉",
            Desc = "矿石出现率翻倍",
            Icon = "gem",
            IsTurret = false,
        }
    end,
    [9] = function()
        return {
            Id = 9,
            Key = "slow",
            Name = "制动系统",
            Desc = "列车速度-15%",
            Icon = "gear",
            IsTurret = false,
        }
    end,
    [10] = function()
        return {
            Id = 10,
            Key = "repair",
            Name = "应急维修",
            Desc = "列车回复30HP",
            Icon = "shield",
            IsTurret = false,
        }
    end,
    [11] = function()
        return {
            Id = 11,
            Key = "armor",
            Name = "装甲强化",
            Desc = "列车最大HP+25",
            Icon = "x2",
            IsTurret = false,
        }
    end,
    [12] = function()
        return {
            Id = 12,
            Key = "multi",
            Name = "双倍搜刮",
            Desc = "采集掉落概率×2",
            Icon = "fairy",
            IsTurret = false,
        }
    end,
    [13] = function()
        return {
            Id = 13,
            Key = "turret_arrow",
            Name = "弓箭炮塔",
            Desc = "解锁弓箭炮塔",
            Icon = "turret_arrow",
            IsTurret = true,
            TurretType = "arrow",
        }
    end,
    [14] = function()
        return {
            Id = 14,
            Key = "turret_minigun",
            Name = "机关枪塔",
            Desc = "解锁机关枪炮塔",
            Icon = "turret_minigun",
            IsTurret = true,
            TurretType = "minigun",
        }
    end,
    [15] = function()
        return {
            Id = 15,
            Key = "turret_flame",
            Name = "喷火炮塔",
            Desc = "解锁喷火炮塔",
            Icon = "turret_flame",
            IsTurret = true,
            TurretType = "flame",
        }
    end,
    [16] = function()
        return {
            Id = 16,
            Key = "turret_sniper",
            Name = "狙击炮塔",
            Desc = "解锁狙击炮塔",
            Icon = "turret_sniper",
            IsTurret = true,
            TurretType = "sniper",
        }
    end,
    [17] = function()
        return {
            Id = 17,
            Key = "turret_electric",
            Name = "电能炮塔",
            Desc = "解锁电能炮塔",
            Icon = "turret_electric",
            IsTurret = true,
            TurretType = "electric",
        }
    end,
    [18] = function()
        return {
            Id = 18,
            Key = "turret_rocket",
            Name = "火箭炮塔",
            Desc = "解锁火箭炮塔",
            Icon = "turret_rocket",
            IsTurret = true,
            TurretType = "rocket",
        }
    end,
}

function CfgS_Upgrades.Get_dCfgUpgrade(id)
    local data = CfgS_Upgrades.dCfgUpgrade[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgUpgrade[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_Upgrades.dCfgUpgrade[id] = data
    return data
end

function CfgS_Upgrades.Get_CfgUpgradeByIndex(index)
    if index < 0 or index >= #CfgS_Upgrades.allCfgUpgrades then
        return nil
    end
    return CfgS_Upgrades.Get_dCfgUpgrade(CfgS_Upgrades.allCfgUpgrades[index + 1])
end

return CfgS_Upgrades
