-- ============================================================================
-- CfgS_Turrets (server)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: Turrets.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgS_Turrets = {}

CfgS_Turrets.dCfgTurret = {}
CfgS_Turrets.allCfgTurrets = {
    "arrow",
    "sniper",
    "flame",
    "electric",
    "rocket",
    "minigun",
}
local _createCfgTurret = {
    ["arrow"] = function()
        return {
            Id = "arrow",
            Range = 220,
            Damage = 8,
            Cooldown = 1,
            ProjType = "arrow",
            ProjSpeed = 300,
            ProjLife = 0.8,
            AoeRadius = 0,
            AoeFalloff = 0,
            ConeHalfAngle = 0,
        }
    end,
    ["sniper"] = function()
        return {
            Id = "sniper",
            Range = 350,
            Damage = 35,
            Cooldown = 5,
            ProjType = "sniper",
            ProjSpeed = 0,
            ProjLife = 0,
            AoeRadius = 0,
            AoeFalloff = 0,
            ConeHalfAngle = 0,
        }
    end,
    ["flame"] = function()
        return {
            Id = "flame",
            Range = 200,
            Damage = 5,
            Cooldown = 0.12,
            ProjType = "flame",
            ProjSpeed = 0,
            ProjLife = 0,
            AoeRadius = 0,
            AoeFalloff = 0,
            ConeHalfAngle = 0.45,
        }
    end,
    ["electric"] = function()
        return {
            Id = "electric",
            Range = 200,
            Damage = 12,
            Cooldown = 0.7,
            ProjType = "electric",
            ProjSpeed = 0,
            ProjLife = 0,
            AoeRadius = 0,
            AoeFalloff = 0,
            ConeHalfAngle = 0,
        }
    end,
    ["rocket"] = function()
        return {
            Id = "rocket",
            Range = 280,
            Damage = 40,
            Cooldown = 8,
            ProjType = "rocket",
            ProjSpeed = 150,
            ProjLife = 0,
            AoeRadius = 80,
            AoeFalloff = 0.5,
            ConeHalfAngle = 0,
        }
    end,
    ["minigun"] = function()
        return {
            Id = "minigun",
            Range = 250,
            Damage = 3,
            Cooldown = 0.1,
            ProjType = "minigun",
            ProjSpeed = 500,
            ProjLife = 0.8,
            AoeRadius = 0,
            AoeFalloff = 0,
            ConeHalfAngle = 0,
        }
    end,
}

function CfgS_Turrets.Get_dCfgTurret(id)
    local data = CfgS_Turrets.dCfgTurret[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgTurret[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_Turrets.dCfgTurret[id] = data
    return data
end

function CfgS_Turrets.Get_CfgTurretByIndex(index)
    if index < 0 or index >= #CfgS_Turrets.allCfgTurrets then
        return nil
    end
    return CfgS_Turrets.Get_dCfgTurret(CfgS_Turrets.allCfgTurrets[index + 1])
end

return CfgS_Turrets
