-- ============================================================================
-- CfgS_Equips (server)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: Equips.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgS_Equips = {}

CfgS_Equips.dCfgEquipSlot = {}
CfgS_Equips.allCfgEquipSlots = {
    1,
    2,
    3,
    4,
    5,
    6,
}
local _createCfgEquipSlot = {
    [1] = function()
        return {
            Id = 1,
            Key = "weapon",
            Name = "武器",
            Icon = "image/equip_weapon_sword_20260421064504.png",
        }
    end,
    [2] = function()
        return {
            Id = 2,
            Key = "accessory",
            Name = "饰品",
            Icon = "image/equip_accessory_necklace_20260421064510.png",
        }
    end,
    [3] = function()
        return {
            Id = 3,
            Key = "ring",
            Name = "戒指",
            Icon = "image/equip_ring_20260421064511.png",
        }
    end,
    [4] = function()
        return {
            Id = 4,
            Key = "hat",
            Name = "帽子",
            Icon = "image/equip_hat_20260421064515.png",
        }
    end,
    [5] = function()
        return {
            Id = 5,
            Key = "clothes",
            Name = "衣服",
            Icon = "image/equip_clothes_20260421064729.png",
        }
    end,
    [6] = function()
        return {
            Id = 6,
            Key = "boots",
            Name = "鞋子",
            Icon = "image/equip_boots_20260421064742.png",
        }
    end,
}

function CfgS_Equips.Get_dCfgEquipSlot(id)
    local data = CfgS_Equips.dCfgEquipSlot[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgEquipSlot[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_Equips.dCfgEquipSlot[id] = data
    return data
end

function CfgS_Equips.Get_CfgEquipSlotByIndex(index)
    if index < 0 or index >= #CfgS_Equips.allCfgEquipSlots then
        return nil
    end
    return CfgS_Equips.Get_dCfgEquipSlot(CfgS_Equips.allCfgEquipSlots[index + 1])
end

CfgS_Equips.dCfgQuality = {}
CfgS_Equips.allCfgQualitys = {
    1,
    2,
    3,
    4,
    5,
}
local _createCfgQuality = {
    [1] = function()
        return {
            Id = 1,
            Key = "common",
            Name = "普通",
            ColorR = 160,
            ColorG = 165,
            ColorB = 175,
            ColorA = 255,
        }
    end,
    [2] = function()
        return {
            Id = 2,
            Key = "uncommon",
            Name = "优秀",
            ColorR = 65,
            ColorG = 170,
            ColorB = 80,
            ColorA = 255,
        }
    end,
    [3] = function()
        return {
            Id = 3,
            Key = "rare",
            Name = "稀有",
            ColorR = 55,
            ColorG = 120,
            ColorB = 210,
            ColorA = 255,
        }
    end,
    [4] = function()
        return {
            Id = 4,
            Key = "epic",
            Name = "史诗",
            ColorR = 150,
            ColorG = 60,
            ColorB = 200,
            ColorA = 255,
        }
    end,
    [5] = function()
        return {
            Id = 5,
            Key = "legend",
            Name = "传说",
            ColorR = 220,
            ColorG = 165,
            ColorB = 30,
            ColorA = 255,
        }
    end,
}

function CfgS_Equips.Get_dCfgQuality(id)
    local data = CfgS_Equips.dCfgQuality[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgQuality[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_Equips.dCfgQuality[id] = data
    return data
end

function CfgS_Equips.Get_CfgQualityByIndex(index)
    if index < 0 or index >= #CfgS_Equips.allCfgQualitys then
        return nil
    end
    return CfgS_Equips.Get_dCfgQuality(CfgS_Equips.allCfgQualitys[index + 1])
end

CfgS_Equips.dCfgEquip = {}
CfgS_Equips.allCfgEquips = {
    1,
    2,
    3,
    4,
    5,
    6,
    7,
}
local _createCfgEquip = {
    [1] = function()
        return {
            Id = 1,
            Key = "sword_iron",
            Slot = "weapon",
            Name = "铁剑",
            Quality = 1,
            Atk = 5,
            Def = 0,
            AtkSpd = 0,
            Hp = 0,
            Speed = 0,
            Icon = "image/equip_weapon_sword_20260421064504.png",
        }
    end,
    [2] = function()
        return {
            Id = 2,
            Key = "axe_war",
            Slot = "weapon",
            Name = "战斧",
            Quality = 2,
            Atk = 8,
            Def = 0,
            AtkSpd = 0,
            Hp = 0,
            Speed = 0,
            Icon = "image/equip_weapon_axe_20260421064553.png",
        }
    end,
    [3] = function()
        return {
            Id = 3,
            Key = "necklace_1",
            Slot = "accessory",
            Name = "护身符",
            Quality = 1,
            Atk = 0,
            Def = 3,
            AtkSpd = 0,
            Hp = 0,
            Speed = 0,
            Icon = "image/equip_accessory_necklace_20260421064510.png",
        }
    end,
    [4] = function()
        return {
            Id = 4,
            Key = "ring_silver",
            Slot = "ring",
            Name = "银戒指",
            Quality = 2,
            Atk = 0,
            Def = 0,
            AtkSpd = 0.1,
            Hp = 0,
            Speed = 0,
            Icon = "image/equip_ring_20260421064511.png",
        }
    end,
    [5] = function()
        return {
            Id = 5,
            Key = "hat_winter",
            Slot = "hat",
            Name = "冬帽",
            Quality = 1,
            Atk = 0,
            Def = 0,
            AtkSpd = 0,
            Hp = 10,
            Speed = 0,
            Icon = "image/equip_hat_20260421064515.png",
        }
    end,
    [6] = function()
        return {
            Id = 6,
            Key = "coat_warm",
            Slot = "clothes",
            Name = "棉衣",
            Quality = 1,
            Atk = 0,
            Def = 5,
            AtkSpd = 0,
            Hp = 0,
            Speed = 0,
            Icon = "image/equip_clothes_20260421064729.png",
        }
    end,
    [7] = function()
        return {
            Id = 7,
            Key = "boots_army",
            Slot = "boots",
            Name = "军靴",
            Quality = 1,
            Atk = 0,
            Def = 0,
            AtkSpd = 0,
            Hp = 0,
            Speed = 0.1,
            Icon = "image/equip_boots_20260421064742.png",
        }
    end,
}

function CfgS_Equips.Get_dCfgEquip(id)
    local data = CfgS_Equips.dCfgEquip[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgEquip[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_Equips.dCfgEquip[id] = data
    return data
end

function CfgS_Equips.Get_CfgEquipByIndex(index)
    if index < 0 or index >= #CfgS_Equips.allCfgEquips then
        return nil
    end
    return CfgS_Equips.Get_dCfgEquip(CfgS_Equips.allCfgEquips[index + 1])
end

return CfgS_Equips
