-- ============================================================================
-- CfgS_MetaUI (server)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: MetaUI.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgS_MetaUI = {}

CfgS_MetaUI.INIT_GOLD = 500 -- 初始金币
CfgS_MetaUI.INIT_DIAMOND = 100 -- 初始钻石
CfgS_MetaUI.INIT_WOOD = 30 -- 初始木材
CfgS_MetaUI.INIT_STONE = 20 -- 初始石材
CfgS_MetaUI.INIT_MAX_LEVEL = 1 -- 初始最高解锁关卡
CfgS_MetaUI.INIT_PLAYER_NAME = "幸存者" -- 初始玩家名
CfgS_MetaUI.INIT_PLAYER_LEVEL = 1 -- 初始玩家等级

CfgS_MetaUI.dCfgTab = {}
CfgS_MetaUI.allCfgTabs = {
    1,
    2,
    3,
    4,
    5,
}
local _createCfgTab = {
    [1] = function()
        return {
            Id = 1,
            Key = "shop",
            Name = "商城",
            Icon = "image/meta_tab_shop_20260421063707.png",
        }
    end,
    [2] = function()
        return {
            Id = 2,
            Key = "equip",
            Name = "装备",
            Icon = "image/meta_tab_equip_20260421063710.png",
        }
    end,
    [3] = function()
        return {
            Id = 3,
            Key = "battle",
            Name = "战斗",
            Icon = "image/meta_tab_battle_20260421063808.png",
        }
    end,
    [4] = function()
        return {
            Id = 4,
            Key = "train",
            Name = "列车",
            Icon = "image/meta_tab_train_20260421063842.png",
        }
    end,
    [5] = function()
        return {
            Id = 5,
            Key = "talent",
            Name = "天赋",
            Icon = "image/meta_tab_talent_20260421063732.png",
        }
    end,
}

function CfgS_MetaUI.Get_dCfgTab(id)
    local data = CfgS_MetaUI.dCfgTab[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgTab[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_MetaUI.dCfgTab[id] = data
    return data
end

function CfgS_MetaUI.Get_CfgTabByIndex(index)
    if index < 0 or index >= #CfgS_MetaUI.allCfgTabs then
        return nil
    end
    return CfgS_MetaUI.Get_dCfgTab(CfgS_MetaUI.allCfgTabs[index + 1])
end

CfgS_MetaUI.dCfgCurrency = {}
CfgS_MetaUI.allCfgCurrencys = {
    1,
    2,
    3,
    4,
}
local _createCfgCurrency = {
    [1] = function()
        return {
            Id = 1,
            Key = "gold",
            Icon = "image/hud_gold_coin.png",
        }
    end,
    [2] = function()
        return {
            Id = 2,
            Key = "diamond",
            Icon = "image/meta_icon_diamond_20260421063718.png",
        }
    end,
    [3] = function()
        return {
            Id = 3,
            Key = "wood",
            Icon = "image/meta_icon_wood_20260421063709.png",
        }
    end,
    [4] = function()
        return {
            Id = 4,
            Key = "stone",
            Icon = "image/meta_icon_stone_20260421063705.png",
        }
    end,
}

function CfgS_MetaUI.Get_dCfgCurrency(id)
    local data = CfgS_MetaUI.dCfgCurrency[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgCurrency[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_MetaUI.dCfgCurrency[id] = data
    return data
end

function CfgS_MetaUI.Get_CfgCurrencyByIndex(index)
    if index < 0 or index >= #CfgS_MetaUI.allCfgCurrencys then
        return nil
    end
    return CfgS_MetaUI.Get_dCfgCurrency(CfgS_MetaUI.allCfgCurrencys[index + 1])
end

CfgS_MetaUI.dCfgChest = {}
CfgS_MetaUI.allCfgChests = {
    1,
    2,
    3,
}
local _createCfgChest = {
    [1] = function()
        return {
            Id = 1,
            Key = "bronze",
            Icon = "image/chest_bronze_20260421064750.png",
        }
    end,
    [2] = function()
        return {
            Id = 2,
            Key = "silver",
            Icon = "image/chest_silver_20260421064733.png",
        }
    end,
    [3] = function()
        return {
            Id = 3,
            Key = "gold",
            Icon = "image/chest_gold_20260421064736.png",
        }
    end,
}

function CfgS_MetaUI.Get_dCfgChest(id)
    local data = CfgS_MetaUI.dCfgChest[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgChest[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_MetaUI.dCfgChest[id] = data
    return data
end

function CfgS_MetaUI.Get_CfgChestByIndex(index)
    if index < 0 or index >= #CfgS_MetaUI.allCfgChests then
        return nil
    end
    return CfgS_MetaUI.Get_dCfgChest(CfgS_MetaUI.allCfgChests[index + 1])
end

return CfgS_MetaUI
