-- ============================================================================
-- CfgS_Resources (server)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: Resources.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgS_Resources = {}

CfgS_Resources.dCfgResource = {}
CfgS_Resources.allCfgResources = {
    "wood",
    "stone",
    "ore",
    "bush",
    "pebble",
}
local _createCfgResource = {
    ["wood"] = function()
        return {
            Id = "wood",
            Freq = 0.35,
            Hp = 80,
            Drop = 2,
        }
    end,
    ["stone"] = function()
        return {
            Id = "stone",
            Freq = 0.3,
            Hp = 100,
            Drop = 2,
        }
    end,
    ["ore"] = function()
        return {
            Id = "ore",
            Freq = 0.1,
            Hp = 150,
            Drop = 1,
        }
    end,
    ["bush"] = function()
        return {
            Id = "bush",
            Freq = 0.15,
            Hp = 50,
            Drop = 1,
        }
    end,
    ["pebble"] = function()
        return {
            Id = "pebble",
            Freq = 0.1,
            Hp = 60,
            Drop = 1,
        }
    end,
}

function CfgS_Resources.Get_dCfgResource(id)
    local data = CfgS_Resources.dCfgResource[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgResource[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_Resources.dCfgResource[id] = data
    return data
end

function CfgS_Resources.Get_CfgResourceByIndex(index)
    if index < 0 or index >= #CfgS_Resources.allCfgResources then
        return nil
    end
    return CfgS_Resources.Get_dCfgResource(CfgS_Resources.allCfgResources[index + 1])
end

return CfgS_Resources
