-- ============================================================================
-- CfgS_MetaData (server)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: MetaData.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgS_MetaData = {}

CfgS_MetaData.dCfgTalent = {}
CfgS_MetaData.allCfgTalents = {
    "hp",
    "atk",
    "atkspd",
    "def",
    "speed",
    "gold",
    "carry",
    "unlock",
}
local _createCfgTalent = {
    ["hp"] = function()
        return {
            Id = "hp",
            MaxLv = 10,
            CostBase = 50,
            CostGrow = 1.3,
        }
    end,
    ["atk"] = function()
        return {
            Id = "atk",
            MaxLv = 10,
            CostBase = 60,
            CostGrow = 1.3,
        }
    end,
    ["atkspd"] = function()
        return {
            Id = "atkspd",
            MaxLv = 8,
            CostBase = 80,
            CostGrow = 1.4,
        }
    end,
    ["def"] = function()
        return {
            Id = "def",
            MaxLv = 8,
            CostBase = 70,
            CostGrow = 1.3,
        }
    end,
    ["speed"] = function()
        return {
            Id = "speed",
            MaxLv = 6,
            CostBase = 60,
            CostGrow = 1.4,
        }
    end,
    ["gold"] = function()
        return {
            Id = "gold",
            MaxLv = 8,
            CostBase = 100,
            CostGrow = 1.5,
        }
    end,
    ["carry"] = function()
        return {
            Id = "carry",
            MaxLv = 5,
            CostBase = 80,
            CostGrow = 1.4,
        }
    end,
    ["unlock"] = function()
        return {
            Id = "unlock",
            MaxLv = 3,
            CostBase = 200,
            CostGrow = 2,
        }
    end,
}

function CfgS_MetaData.Get_dCfgTalent(id)
    local data = CfgS_MetaData.dCfgTalent[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgTalent[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_MetaData.dCfgTalent[id] = data
    return data
end

function CfgS_MetaData.Get_CfgTalentByIndex(index)
    if index < 0 or index >= #CfgS_MetaData.allCfgTalents then
        return nil
    end
    return CfgS_MetaData.Get_dCfgTalent(CfgS_MetaData.allCfgTalents[index + 1])
end

CfgS_MetaData.dCfgLevel = {}
CfgS_MetaData.allCfgLevels = {
    1,
    2,
    3,
    4,
    5,
    6,
}
local _createCfgLevel = {
    [1] = function()
        return {
            Id = 1,
            Waves = 5,
            RewardGold = 50,
            Chest = "bronze",
            Unlocked = true,
        }
    end,
    [2] = function()
        return {
            Id = 2,
            Waves = 7,
            RewardGold = 80,
            Chest = "bronze",
            Unlocked = false,
        }
    end,
    [3] = function()
        return {
            Id = 3,
            Waves = 8,
            RewardGold = 100,
            Chest = "silver",
            Unlocked = false,
        }
    end,
    [4] = function()
        return {
            Id = 4,
            Waves = 10,
            RewardGold = 150,
            Chest = "silver",
            Unlocked = false,
        }
    end,
    [5] = function()
        return {
            Id = 5,
            Waves = 12,
            RewardGold = 200,
            Chest = "gold",
            Unlocked = false,
        }
    end,
    [6] = function()
        return {
            Id = 6,
            Waves = 15,
            RewardGold = 300,
            Chest = "gold",
            Unlocked = false,
        }
    end,
}

function CfgS_MetaData.Get_dCfgLevel(id)
    local data = CfgS_MetaData.dCfgLevel[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgLevel[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_MetaData.dCfgLevel[id] = data
    return data
end

function CfgS_MetaData.Get_CfgLevelByIndex(index)
    if index < 0 or index >= #CfgS_MetaData.allCfgLevels then
        return nil
    end
    return CfgS_MetaData.Get_dCfgLevel(CfgS_MetaData.allCfgLevels[index + 1])
end

CfgS_MetaData.dCfgTurretUpgrade = {}
CfgS_MetaData.allCfgTurretUpgrades = {
    "arrow",
    "minigun",
    "flame",
    "sniper",
    "electric",
    "rocket",
}
local _createCfgTurretUpgrade = {
    ["arrow"] = function()
        return {
            Id = "arrow",
            MaxLv = 5,
            FragBase = 5,
            FragGrow = 1.5,
        }
    end,
    ["minigun"] = function()
        return {
            Id = "minigun",
            MaxLv = 5,
            FragBase = 8,
            FragGrow = 1.5,
        }
    end,
    ["flame"] = function()
        return {
            Id = "flame",
            MaxLv = 5,
            FragBase = 8,
            FragGrow = 1.5,
        }
    end,
    ["sniper"] = function()
        return {
            Id = "sniper",
            MaxLv = 5,
            FragBase = 10,
            FragGrow = 1.6,
        }
    end,
    ["electric"] = function()
        return {
            Id = "electric",
            MaxLv = 5,
            FragBase = 10,
            FragGrow = 1.6,
        }
    end,
    ["rocket"] = function()
        return {
            Id = "rocket",
            MaxLv = 5,
            FragBase = 12,
            FragGrow = 1.8,
        }
    end,
}

function CfgS_MetaData.Get_dCfgTurretUpgrade(id)
    local data = CfgS_MetaData.dCfgTurretUpgrade[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgTurretUpgrade[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_MetaData.dCfgTurretUpgrade[id] = data
    return data
end

function CfgS_MetaData.Get_CfgTurretUpgradeByIndex(index)
    if index < 0 or index >= #CfgS_MetaData.allCfgTurretUpgrades then
        return nil
    end
    return CfgS_MetaData.Get_dCfgTurretUpgrade(CfgS_MetaData.allCfgTurretUpgrades[index + 1])
end

return CfgS_MetaData
