-- ============================================================================
-- CfgS_Resources (server)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: Resources.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgS_Resources = {}

CfgS_Resources.dCfgResource = {}
CfgS_Resources.allCfgResources = {
    1,
    2,
    3,
    4,
    5,
}
local _createCfgResource = {
    [1] = function()
        return {
            Id = 1,
            Key = "wood",
            Name = "木材",
            Freq = 0.35,
            Hp = 80,
            Drop = 2,
        }
    end,
    [2] = function()
        return {
            Id = 2,
            Key = "stone",
            Name = "岩石",
            Freq = 0.3,
            Hp = 100,
            Drop = 2,
        }
    end,
    [3] = function()
        return {
            Id = 3,
            Key = "ore",
            Name = "矿石",
            Freq = 0.1,
            Hp = 150,
            Drop = 1,
        }
    end,
    [4] = function()
        return {
            Id = 4,
            Key = "bush",
            Name = "灌木",
            Freq = 0.15,
            Hp = 50,
            Drop = 1,
        }
    end,
    [5] = function()
        return {
            Id = 5,
            Key = "pebble",
            Name = "碎石",
            Freq = 0.1,
            Hp = 60,
            Drop = 1,
        }
    end,
}

function CfgS_Resources.Get_dCfgResource(id)
    local data = CfgS_Resources.dCfgResource[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgResource[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_Resources.dCfgResource[id] = data
    return data
end

function CfgS_Resources.Get_CfgResourceByIndex(index)
    if index < 0 or index >= #CfgS_Resources.allCfgResources then
        return nil
    end
    return CfgS_Resources.Get_dCfgResource(CfgS_Resources.allCfgResources[index + 1])
end

return CfgS_Resources
