-- ============================================================================
-- CfgS_MetaData (server)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: MetaData.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgS_MetaData = {}

CfgS_MetaData.dCfgTalent = {}
CfgS_MetaData.allCfgTalents = {
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
}
local _createCfgTalent = {
    [1] = function()
        return {
            Id = 1,
            Key = "hp",
            Name = "生命强化",
            Desc = "列车最大HP+10",
            MaxLv = 10,
            CostBase = 50,
            CostGrow = 1.3,
            Icon = "image/talent_hp_20260421065056.png",
        }
    end,
    [2] = function()
        return {
            Id = 2,
            Key = "atk",
            Name = "力量提升",
            Desc = "攻击力+1",
            MaxLv = 10,
            CostBase = 60,
            CostGrow = 1.3,
            Icon = "image/talent_atk_20260421065251.png",
        }
    end,
    [3] = function()
        return {
            Id = 3,
            Key = "atkspd",
            Name = "疾速打击",
            Desc = "攻击速度+5%",
            MaxLv = 8,
            CostBase = 80,
            CostGrow = 1.4,
            Icon = "image/talent_atkspd_20260421065058.png",
        }
    end,
    [4] = function()
        return {
            Id = 4,
            Key = "def",
            Name = "铁壁防御",
            Desc = "减少列车受伤-5%",
            MaxLv = 8,
            CostBase = 70,
            CostGrow = 1.3,
            Icon = "image/talent_def_20260421065053.png",
        }
    end,
    [5] = function()
        return {
            Id = 5,
            Key = "speed",
            Name = "轻身术",
            Desc = "移动速度+8%",
            MaxLv = 6,
            CostBase = 60,
            CostGrow = 1.4,
            Icon = "image/talent_speed_20260421065223.png",
        }
    end,
    [6] = function()
        return {
            Id = 6,
            Key = "gold",
            Name = "聚财术",
            Desc = "金币收益+10%",
            MaxLv = 8,
            CostBase = 100,
            CostGrow = 1.5,
            Icon = "image/talent_gold_20260421065059.png",
        }
    end,
    [7] = function()
        return {
            Id = 7,
            Key = "carry",
            Name = "负重训练",
            Desc = "携带上限+2",
            MaxLv = 5,
            CostBase = 80,
            CostGrow = 1.4,
            Icon = "image/talent_carry_20260421065057.png",
        }
    end,
    [8] = function()
        return {
            Id = 8,
            Key = "unlock",
            Name = "求生本能",
            Desc = "解锁新技能",
            MaxLv = 3,
            CostBase = 200,
            CostGrow = 2,
            Icon = "image/talent_unlock_20260421065109.png",
        }
    end,
}

function CfgS_MetaData.Get_dCfgTalent(id)
    local data = CfgS_MetaData.dCfgTalent[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgTalent[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_MetaData.dCfgTalent[id] = data
    return data
end

function CfgS_MetaData.Get_CfgTalentByIndex(index)
    if index < 0 or index >= #CfgS_MetaData.allCfgTalents then
        return nil
    end
    return CfgS_MetaData.Get_dCfgTalent(CfgS_MetaData.allCfgTalents[index + 1])
end

CfgS_MetaData.dCfgLevel = {}
CfgS_MetaData.allCfgLevels = {
    1,
    2,
    3,
    4,
    5,
    6,
}
local _createCfgLevel = {
    [1] = function()
        return {
            Id = 1,
            Name = "荒原前哨",
            Waves = 5,
            RewardGold = 50,
            Chest = "bronze",
            Unlocked = true,
        }
    end,
    [2] = function()
        return {
            Id = 2,
            Name = "冰封隧道",
            Waves = 7,
            RewardGold = 80,
            Chest = "bronze",
            Unlocked = false,
        }
    end,
    [3] = function()
        return {
            Id = 3,
            Name = "暴风雪谷",
            Waves = 8,
            RewardGold = 100,
            Chest = "silver",
            Unlocked = false,
        }
    end,
    [4] = function()
        return {
            Id = 4,
            Name = "死寂车站",
            Waves = 10,
            RewardGold = 150,
            Chest = "silver",
            Unlocked = false,
        }
    end,
    [5] = function()
        return {
            Id = 5,
            Name = "钢铁废墟",
            Waves = 12,
            RewardGold = 200,
            Chest = "gold",
            Unlocked = false,
        }
    end,
    [6] = function()
        return {
            Id = 6,
            Name = "末日核心",
            Waves = 15,
            RewardGold = 300,
            Chest = "gold",
            Unlocked = false,
        }
    end,
}

function CfgS_MetaData.Get_dCfgLevel(id)
    local data = CfgS_MetaData.dCfgLevel[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgLevel[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_MetaData.dCfgLevel[id] = data
    return data
end

function CfgS_MetaData.Get_CfgLevelByIndex(index)
    if index < 0 or index >= #CfgS_MetaData.allCfgLevels then
        return nil
    end
    return CfgS_MetaData.Get_dCfgLevel(CfgS_MetaData.allCfgLevels[index + 1])
end

CfgS_MetaData.dCfgTurretUpgrade = {}
CfgS_MetaData.allCfgTurretUpgrades = {
    1,
    2,
    3,
    4,
    5,
    6,
}
local _createCfgTurretUpgrade = {
    [1] = function()
        return {
            Id = 1,
            Key = "arrow",
            Name = "弓箭炮塔",
            MaxLv = 5,
            FragBase = 5,
            FragGrow = 1.5,
            Icon = "image/turret_arrow_v3_20260420035036.png",
        }
    end,
    [2] = function()
        return {
            Id = 2,
            Key = "minigun",
            Name = "机关枪塔",
            MaxLv = 5,
            FragBase = 8,
            FragGrow = 1.5,
            Icon = "image/turret_minigun_v3_20260420035022.png",
        }
    end,
    [3] = function()
        return {
            Id = 3,
            Key = "flame",
            Name = "喷火炮塔",
            MaxLv = 5,
            FragBase = 8,
            FragGrow = 1.5,
            Icon = "image/edited_turret_flame_nofire_20260423065123.png",
        }
    end,
    [4] = function()
        return {
            Id = 4,
            Key = "sniper",
            Name = "狙击炮塔",
            MaxLv = 5,
            FragBase = 10,
            FragGrow = 1.6,
            Icon = "image/turret_sniper_v3_20260420035021.png",
        }
    end,
    [5] = function()
        return {
            Id = 5,
            Key = "electric",
            Name = "电能炮塔",
            MaxLv = 5,
            FragBase = 10,
            FragGrow = 1.6,
            Icon = "image/turret_electric_v10_20260423040517.png",
        }
    end,
    [6] = function()
        return {
            Id = 6,
            Key = "rocket",
            Name = "火箭炮塔",
            MaxLv = 5,
            FragBase = 12,
            FragGrow = 1.8,
            Icon = "image/turret_rocket_v3_20260420035019.png",
        }
    end,
}

function CfgS_MetaData.Get_dCfgTurretUpgrade(id)
    local data = CfgS_MetaData.dCfgTurretUpgrade[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgTurretUpgrade[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgS_MetaData.dCfgTurretUpgrade[id] = data
    return data
end

function CfgS_MetaData.Get_CfgTurretUpgradeByIndex(index)
    if index < 0 or index >= #CfgS_MetaData.allCfgTurretUpgrades then
        return nil
    end
    return CfgS_MetaData.Get_dCfgTurretUpgrade(CfgS_MetaData.allCfgTurretUpgrades[index + 1])
end

return CfgS_MetaData
