-- ============================================================================
-- CfgS_Colors (server)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: Colors.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgS_Colors = {}

CfgS_Colors.SNOW1 = { 155, 160, 168 } -- 脏灰雪
CfgS_Colors.SNOW2 = { 130, 138, 148 } -- 深灰雪纹
CfgS_Colors.SNOW3 = { 170, 175, 182 } -- 浅灰
CfgS_Colors.SNOW_DARK = { 105, 112, 125 } -- 阴影区
CfgS_Colors.PATH = { 85, 78, 68 } -- 暗褐冻土
CfgS_Colors.PATH_LIGHT = { 100, 92, 80 } -- 碎石亮面
CfgS_Colors.PATH_DARK = { 60, 55, 45 } -- 泥坑暗部
CfgS_Colors.PATH_EDGE = { 120, 125, 135 } -- 路缘过渡
CfgS_Colors.TRAIN_BODY = { 52, 55, 50 } -- 暗铁灰车身
CfgS_Colors.TRAIN_DARK = { 35, 38, 32 } -- 深暗面
CfgS_Colors.TRAIN_LIGHT = { 72, 78, 68 } -- 微弱高光
CfgS_Colors.TRAIN_ROOF = { 40, 42, 38 } -- 车顶
CfgS_Colors.TRAIN_METAL = { 65, 68, 62 } -- 金属件
CfgS_Colors.TRAIN_WINDOW = { 75, 105, 130 } -- 脏窗玻璃
CfgS_Colors.TRAIN_WINDOW2 = { 55, 80, 105 } -- 深色窗
CfgS_Colors.TRAIN_STRIPE = { 140, 35, 25 } -- 暗血红装饰
CfgS_Colors.TRAIN_STRIPE2 = { 110, 25, 18 } -- 深红锈
CfgS_Colors.TRAIN_BRASS = { 145, 120, 55 } -- 氧化铜
CfgS_Colors.TRAIN_BRASS2 = { 170, 145, 70 } -- 铜亮面
CfgS_Colors.TRAIN_BRASS3 = { 110, 90, 40 } -- 铜暗面
CfgS_Colors.TRAIN_SMOKE = { 38, 35, 30 } -- 烟囱黑
CfgS_Colors.TRAIN_SMOKE2 = { 25, 22, 18 } -- 烟囱暗
CfgS_Colors.TRAIN_RIVET = { 80, 85, 75 } -- 锈铆钉
CfgS_Colors.TRAIN_FRAME = { 30, 32, 28 } -- 暗轮廓
CfgS_Colors.TRAIN_PLATE = { 120, 105, 55 } -- 锈铭牌
CfgS_Colors.TRAIN_CAB_BG = { 45, 48, 42 } -- 驾驶室
CfgS_Colors.TRAIN_PIPE = { 95, 90, 80 } -- 锈管道
CfgS_Colors.RAIL_COLOR = { 75, 78, 85 } -- 暗铁轨
CfgS_Colors.RAIL_LIGHT = { 100, 105, 115 } -- 磨亮面
CfgS_Colors.SLEEPER_COLOR = { 70, 60, 42 } -- 腐朽枕木
CfgS_Colors.SLEEPER_DARK = { 48, 40, 28 } -- 枕木暗面
CfgS_Colors.BALLAST_COLOR = { 80, 75, 65 } -- 暗碎石
CfgS_Colors.SUBMIT_BG = { 55, 58, 65, 220 } -- 提交区背景
CfgS_Colors.SUBMIT_BORDER = { 85, 90, 100 } -- 提交区边框
CfgS_Colors.SUBMIT_FULL = { 50, 130, 80 } -- 已满暗绿
CfgS_Colors.HUD_BG = { 18, 20, 28, 240 } -- HUD背景
CfgS_Colors.HUD_BORDER = { 40, 45, 58 } -- HUD边框
CfgS_Colors.HUD_TEXT = { 175, 180, 190 } -- HUD文字
CfgS_Colors.TRUNK = { 55, 45, 35 } -- 黑褐树干
CfgS_Colors.TRUNK_DARK = { 35, 28, 20 } -- 腐烂暗部
CfgS_Colors.TREE_SNOW = { 140, 148, 160 } -- 灰雪
CfgS_Colors.TREE_BARE = { 65, 52, 40 } -- 枯枝
CfgS_Colors.TREE_DARK = { 45, 38, 28 } -- 暗枝
CfgS_Colors.SNOWDRIFT1 = { 148, 155, 165 } -- 脏雪堆
CfgS_Colors.SNOWDRIFT2 = { 120, 128, 140 } -- 深灰雪
CfgS_Colors.RUIN_COLOR = { 68, 62, 55 } -- 废墟残骸
CfgS_Colors.WOOD_COLOR = { 110, 78, 40 } -- 暗木色
CfgS_Colors.STONE_COLOR = { 95, 95, 105 } -- 暗岩灰
CfgS_Colors.ORE_COLOR = { 65, 120, 170 } -- 深蓝矿脉
CfgS_Colors.BUSH_COLOR = { 60, 100, 50 } -- 深绿灌木
CfgS_Colors.PEBBLE_COLOR = { 130, 125, 115 } -- 浅灰碎石
CfgS_Colors.GOLD_COLOR = { 200, 165, 40 } -- 暗金
CfgS_Colors.ZOMBIE_SKIN = { 85, 110, 72 } -- 腐肉绿
CfgS_Colors.ZOMBIE_DARK = { 50, 65, 38 } -- 深腐色
CfgS_Colors.ZOMBIE_EYE = { 200, 35, 20 } -- 血红眼
CfgS_Colors.ZOMBIE_CLOTH = { 55, 48, 42 } -- 破烂深色
CfgS_Colors.PLAYER_COAT = { 125, 55, 35 } -- 暗红破旧大衣
CfgS_Colors.PLAYER_SKIN = { 185, 155, 130 } -- 偏暗肤色
CfgS_Colors.PLAYER_PANTS = { 48, 50, 58 } -- 深灰裤
CfgS_Colors.PLAYER_BOOT = { 38, 35, 28 } -- 泥靴
CfgS_Colors.PLAYER_HAT = { 105, 42, 28 } -- 暗红帽
CfgS_Colors.PLAYER_SCARF = { 145, 125, 40 } -- 脏黄围巾
CfgS_Colors.TEXT_WHITE = { 220, 225, 230 } -- 偏灰白
CfgS_Colors.TEXT_DARK = { 15, 18, 25 } -- 深色
CfgS_Colors.TEXT_DIM = { 100, 108, 120 } -- 暗灰
CfgS_Colors.TEXT_RED = { 190, 50, 35 } -- 暗血红
CfgS_Colors.CARD_BG = { 28, 32, 42 } -- 卡片背景
CfgS_Colors.CARD_BORDER = { 55, 60, 75 } -- 卡片边框
CfgS_Colors.CARD_GLOW = { 70, 140, 200 } -- 卡片发光
CfgS_Colors.BLOOD_COLOR = { 180, 30, 20 } -- 飙血颜色
CfgS_Colors.BG_DARK = { 18, 20, 28, 255 } -- 最深背景
CfgS_Colors.BG_PANEL = { 28, 32, 42, 255 } -- 面板背景
CfgS_Colors.BG_CARD = { 38, 42, 55, 255 } -- 卡片背景
CfgS_Colors.BG_INPUT = { 22, 25, 35, 255 } -- 输入框背景
CfgS_Colors.BAR_BG = { 14, 16, 22, 245 } -- 顶/底栏背景
CfgS_Colors.BAR_BORDER = { 45, 50, 65, 255 } -- 栏边框
CfgS_Colors.TAB_ACTIVE = { 70, 140, 200, 255 } -- 激活Tab颜色
CfgS_Colors.TAB_INACTIVE = { 100, 108, 120, 255 } -- 未激活Tab
CfgS_Colors.TAB_BG = { 22, 25, 35, 240 } -- Tab背景
CfgS_Colors.BTN_PRIMARY = { 55, 130, 85, 255 } -- 主按钮暗绿
CfgS_Colors.BTN_SECONDARY = { 50, 55, 70, 255 } -- 次按钮
CfgS_Colors.BTN_DANGER = { 160, 45, 35, 255 } -- 危险按钮
CfgS_Colors.BTN_GOLD = { 180, 145, 40, 255 } -- 金色按钮
CfgS_Colors.META_TEXT_WHITE = { 220, 225, 230, 255 } -- 白色文字
CfgS_Colors.META_TEXT_GRAY = { 130, 138, 150, 255 } -- 灰色文字
CfgS_Colors.META_TEXT_DIM = { 80, 85, 95, 255 } -- 暗灰文字
CfgS_Colors.META_TEXT_GOLD = { 220, 185, 50, 255 } -- 金色文字
CfgS_Colors.META_TEXT_GREEN = { 65, 180, 90, 255 } -- 绿色文字
CfgS_Colors.META_TEXT_RED = { 200, 55, 40, 255 } -- 红色文字
CfgS_Colors.DIVIDER = { 40, 45, 58, 255 } -- 分割线

return CfgS_Colors
