-- ============================================================================
-- CfgS_GameConfig (server)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: GameConfig.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgS_GameConfig = {}

CfgS_GameConfig.BASE_SCROLL_SPEED = 30 -- 基础滚动速度 px/s
CfgS_GameConfig.SCROLL_SPEED_PER_LEVEL = 1.5 -- 每级加速
CfgS_GameConfig.PATH_WIDTH_RATIO = 0.3 -- 路径宽度占屏幕比例
CfgS_GameConfig.MAX_HP = 100 -- 列车最大生命值
CfgS_GameConfig.HP_REGEN = 0 -- 列车每秒自动回复
CfgS_GameConfig.SPEED = 185 -- 玩家移动速度
CfgS_GameConfig.W = 22 -- 玩家宽度
CfgS_GameConfig.H = 32 -- 玩家高度
CfgS_GameConfig.MAX_CARRY = 10 -- 最大携带数
CfgS_GameConfig.AUTO_ATTACK_RANGE = 48 -- 自动攻击/采集范围
CfgS_GameConfig.AUTO_ATTACK_INTERVAL = 0.35 -- 攻击间隔(秒)
CfgS_GameConfig.ATK = 30 -- 玩家基础攻击力
CfgS_GameConfig.ATK_ZOMBIE = 30 -- 对丧尸攻击力
CfgS_GameConfig.SPAWN_INTERVAL = 4 -- 基础丧尸生成间隔(秒)
CfgS_GameConfig.SPAWN_INTERVAL_MIN = 1 -- 最小生成间隔(秒)
CfgS_GameConfig.SPAWN_INTERVAL_REDUCE = 0.3 -- 每级减少间隔(秒)
CfgS_GameConfig.SPEED = 30 -- 丧尸移动速度 px/s
CfgS_GameConfig.SPEED_PER_LEVEL = 1.5 -- 每级加速
CfgS_GameConfig.SIZE = 20 -- 碰撞半径
CfgS_GameConfig.HP = 3 -- 丧尸基础生命值(旧,实际用zombieType)
CfgS_GameConfig.DAMAGE = 8 -- 对列车伤害
CfgS_GameConfig.ATK_INTERVAL = 1.2 -- 攻击列车间隔
CfgS_GameConfig.MAX_BASE = 8 -- 基础最大丧尸数
CfgS_GameConfig.MAX_PER_LEVEL = 2 -- 每级增加最大丧尸数
CfgS_GameConfig.MAX_CAP = 30 -- 绝对上限
CfgS_GameConfig.TYPE1_BASE_HP = 80 -- 白T恤僵尸基础HP
CfgS_GameConfig.TYPE2_BASE_HP = 100 -- 棕外套僵尸基础HP
CfgS_GameConfig.HP_PER_3LEVELS = 5 -- 每3级+HP
CfgS_GameConfig.RES_INTERVAL = 1.4 -- 资源生成间隔
CfgS_GameConfig.RES_PER_SPAWN_MIN = 1 -- 每次最少生成
CfgS_GameConfig.RES_PER_SPAWN_MAX = 2 -- 每次最多生成
CfgS_GameConfig.RES_SIZE = 28 -- 资源节点视觉大小
CfgS_GameConfig.DECO_INTERVAL = 2.5 -- 装饰物生成间隔
CfgS_GameConfig.DECO_PER_SPAWN = 1 -- 每次装饰物数量
CfgS_GameConfig.BASE_TARGET = 13 -- 基础提交目标
CfgS_GameConfig.TARGET_GROWTH = 1.35 -- 目标增长系数
CfgS_GameConfig.GOLD_PER_SUBMIT = 3 -- 提交获得金币
CfgS_GameConfig.GOLD_PER_LEVEL = 25 -- 升级获得金币
CfgS_GameConfig.LEVEL_DIST_TARGET = 1000 -- 每关行驶目标距离(米)
CfgS_GameConfig.SUBMIT_BOX_W = 44 -- 提交区域宽度
CfgS_GameConfig.SUBMIT_BOX_H = 44 -- 提交区域高度

return CfgS_GameConfig
