-- ============================================================================
-- CfgC_GameConfig (client)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: GameConfig.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgC_GameConfig = {}

CfgC_GameConfig.TRAIN.MAX_HP = 100 -- 列车最大生命值
CfgC_GameConfig.TRAIN.HP_REGEN = 0 -- 列车每秒自动回复
CfgC_GameConfig.PLAYER.SPEED = 185 -- 移动速度 px/s
CfgC_GameConfig.PLAYER.WIDTH = 22 -- 碰撞宽度
CfgC_GameConfig.PLAYER.HEIGHT = 32 -- 碰撞高度
CfgC_GameConfig.PLAYER.MAX_CARRY = 10 -- 最大携带量
CfgC_GameConfig.PLAYER.AUTO_ATTACK_RANGE = 48 -- 自动攻击范围 px
CfgC_GameConfig.PLAYER.AUTO_ATTACK_INTERVAL = 0.35 -- 攻击间隔(秒)
CfgC_GameConfig.PLAYER.ATK = 30 -- 基础攻击力(资源)
CfgC_GameConfig.PLAYER.ATK_ZOMBIE = 30 -- 对僵尸攻击力
CfgC_GameConfig.SCROLL.BASE_SPEED = 30 -- 基础滚动速度 px/s
CfgC_GameConfig.SCROLL.SPEED_PER_LEVEL = 1.5 -- 每级加速
CfgC_GameConfig.SCROLL.PATH_WIDTH_RATIO = 0.3 -- 路径宽度占屏幕比例
CfgC_GameConfig.SCROLL.LEVEL_DIST_TARGET = 1000 -- 每关行驶目标距离
CfgC_GameConfig.ZOMBIE.SPAWN_INTERVAL = 4 -- 基础生成间隔(秒)
CfgC_GameConfig.ZOMBIE.SPAWN_INTERVAL_MIN = 1 -- 最小生成间隔(秒)
CfgC_GameConfig.ZOMBIE.SPAWN_INTERVAL_REDUCE = 0.3 -- 每级减少间隔(秒)
CfgC_GameConfig.ZOMBIE.SPEED = 30 -- 移动速度 px/s
CfgC_GameConfig.ZOMBIE.SPEED_PER_LEVEL = 1.5 -- 每级加速
CfgC_GameConfig.ZOMBIE.SIZE = 20 -- 碰撞半径
CfgC_GameConfig.ZOMBIE.HP_TYPE1 = 80 -- 白T恤僵尸基础HP
CfgC_GameConfig.ZOMBIE.HP_TYPE2 = 100 -- 棕外套僵尸基础HP
CfgC_GameConfig.ZOMBIE.HP_GROW_PER_3LV = 5 -- 每3级HP增长
CfgC_GameConfig.ZOMBIE.DAMAGE = 8 -- 对列车伤害
CfgC_GameConfig.ZOMBIE.ATK_INTERVAL = 1.2 -- 攻击列车间隔(秒)
CfgC_GameConfig.ZOMBIE.MAX_BASE = 8 -- 基础最大数量
CfgC_GameConfig.ZOMBIE.MAX_PER_LEVEL = 2 -- 每级增加数量
CfgC_GameConfig.ZOMBIE.MAX_CAP = 30 -- 绝对上限
CfgC_GameConfig.ZOMBIE.KILL_REWARD = 5 -- 击杀金币奖励
CfgC_GameConfig.ECONOMY.BASE_TARGET = 13 -- 基础提交目标
CfgC_GameConfig.ECONOMY.TARGET_GROWTH = 1.35 -- 目标增长倍率
CfgC_GameConfig.ECONOMY.GOLD_PER_SUBMIT = 3 -- 每次提交金币
CfgC_GameConfig.ECONOMY.GOLD_PER_LEVEL = 25 -- 每级奖励金币
CfgC_GameConfig.ECONOMY.SUBMIT_BOX_W = 44 -- 提交区域宽
CfgC_GameConfig.ECONOMY.SUBMIT_BOX_H = 44 -- 提交区域高
CfgC_GameConfig.SPAWN.INTERVAL = 1.4 -- 资源生成间隔(秒)
CfgC_GameConfig.SPAWN.PER_SPAWN_MIN = 1 -- 每次最少生成
CfgC_GameConfig.SPAWN.PER_SPAWN_MAX = 2 -- 每次最多生成
CfgC_GameConfig.SPAWN.RES_SIZE = 28 -- 节点视觉大小 px
CfgC_GameConfig.SPAWN.DECO_INTERVAL = 2.5 -- 装饰物生成间隔
CfgC_GameConfig.SPAWN.DECO_PER_SPAWN = 1 -- 装饰物每次生成数

return CfgC_GameConfig
