-- ============================================================================
-- CfgC_Upgrades (client)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: Upgrades.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgC_Upgrades = {}

CfgC_Upgrades.dCfgUpgrade = {}
CfgC_Upgrades.allCfgUpgrades = {
    "speed",
    "carry",
    "atk",
    "atkspd",
    "range",
    "gold",
    "spawn",
    "ore_luck",
    "slow",
    "repair",
    "armor",
    "multi",
    "turret_arrow",
    "turret_minigun",
    "turret_flame",
    "turret_sniper",
    "turret_electric",
    "turret_rocket",
}
local _createCfgUpgrade = {
    ["speed"] = function()
        return {
            Id = "speed",
            Name = "急行军",
            Desc = "移动速度+25%",
            Icon = "boot",
            IsTurret = false,
        }
    end,
    ["carry"] = function()
        return {
            Id = "carry",
            Name = "军用背包",
            Desc = "携带上限+5",
            Icon = "bag",
            IsTurret = false,
        }
    end,
    ["atk"] = function()
        return {
            Id = "atk",
            Name = "利刃强化",
            Desc = "攻击力+1",
            Icon = "sword",
            IsTurret = false,
        }
    end,
    ["atkspd"] = function()
        return {
            Id = "atkspd",
            Name = "疾风斩",
            Desc = "攻击速度+30%",
            Icon = "wind",
            IsTurret = false,
        }
    end,
    ["range"] = function()
        return {
            Id = "range",
            Name = "长臂猿",
            Desc = "攻击范围+35%",
            Icon = "magnet",
            IsTurret = false,
        }
    end,
    ["gold"] = function()
        return {
            Id = "gold",
            Name = "物资交换",
            Desc = "提交金币+50%",
            Icon = "coin",
            IsTurret = false,
        }
    end,
    ["spawn"] = function()
        return {
            Id = "spawn",
            Name = "丰收区域",
            Desc = "资源生成+30%",
            Icon = "star",
            IsTurret = false,
        }
    end,
    ["ore_luck"] = function()
        return {
            Id = "ore_luck",
            Name = "探矿直觉",
            Desc = "矿石出现率翻倍",
            Icon = "gem",
            IsTurret = false,
        }
    end,
    ["slow"] = function()
        return {
            Id = "slow",
            Name = "制动系统",
            Desc = "列车速度-15%",
            Icon = "gear",
            IsTurret = false,
        }
    end,
    ["repair"] = function()
        return {
            Id = "repair",
            Name = "应急维修",
            Desc = "列车回复30HP",
            Icon = "shield",
            IsTurret = false,
        }
    end,
    ["armor"] = function()
        return {
            Id = "armor",
            Name = "装甲强化",
            Desc = "列车最大HP+25",
            Icon = "x2",
            IsTurret = false,
        }
    end,
    ["multi"] = function()
        return {
            Id = "multi",
            Name = "双倍搜刮",
            Desc = "采集掉落概率×2",
            Icon = "fairy",
            IsTurret = false,
        }
    end,
    ["turret_arrow"] = function()
        return {
            Id = "turret_arrow",
            Name = "弓箭炮塔",
            Desc = "解锁弓箭炮塔",
            Icon = "turret_arrow",
            IsTurret = true,
            TurretType = "arrow",
        }
    end,
    ["turret_minigun"] = function()
        return {
            Id = "turret_minigun",
            Name = "机关枪塔",
            Desc = "解锁机关枪炮塔",
            Icon = "turret_minigun",
            IsTurret = true,
            TurretType = "minigun",
        }
    end,
    ["turret_flame"] = function()
        return {
            Id = "turret_flame",
            Name = "喷火炮塔",
            Desc = "解锁喷火炮塔",
            Icon = "turret_flame",
            IsTurret = true,
            TurretType = "flame",
        }
    end,
    ["turret_sniper"] = function()
        return {
            Id = "turret_sniper",
            Name = "狙击炮塔",
            Desc = "解锁狙击炮塔",
            Icon = "turret_sniper",
            IsTurret = true,
            TurretType = "sniper",
        }
    end,
    ["turret_electric"] = function()
        return {
            Id = "turret_electric",
            Name = "电能炮塔",
            Desc = "解锁电能炮塔",
            Icon = "turret_electric",
            IsTurret = true,
            TurretType = "electric",
        }
    end,
    ["turret_rocket"] = function()
        return {
            Id = "turret_rocket",
            Name = "火箭炮塔",
            Desc = "解锁火箭炮塔",
            Icon = "turret_rocket",
            IsTurret = true,
            TurretType = "rocket",
        }
    end,
}

function CfgC_Upgrades.Get_dCfgUpgrade(id)
    local data = CfgC_Upgrades.dCfgUpgrade[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgUpgrade[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgC_Upgrades.dCfgUpgrade[id] = data
    return data
end

function CfgC_Upgrades.Get_CfgUpgradeByIndex(index)
    if index < 0 or index >= #CfgC_Upgrades.allCfgUpgrades then
        return nil
    end
    return CfgC_Upgrades.Get_dCfgUpgrade(CfgC_Upgrades.allCfgUpgrades[index + 1])
end

return CfgC_Upgrades
