-- ============================================================================
-- CfgC_Resources (client)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: Resources.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgC_Resources = {}

CfgC_Resources.dCfgResource = {}
CfgC_Resources.allCfgResources = {
    "wood",
    "stone",
    "ore",
    "bush",
    "pebble",
}
local _createCfgResource = {
    ["wood"] = function()
        return {
            Id = "wood",
            Name = "木材",
            Freq = 0.35,
            Hp = 80,
            Drop = 2,
        }
    end,
    ["stone"] = function()
        return {
            Id = "stone",
            Name = "岩石",
            Freq = 0.3,
            Hp = 100,
            Drop = 2,
        }
    end,
    ["ore"] = function()
        return {
            Id = "ore",
            Name = "矿石",
            Freq = 0.1,
            Hp = 150,
            Drop = 1,
        }
    end,
    ["bush"] = function()
        return {
            Id = "bush",
            Name = "灌木",
            Freq = 0.15,
            Hp = 50,
            Drop = 1,
        }
    end,
    ["pebble"] = function()
        return {
            Id = "pebble",
            Name = "碎石",
            Freq = 0.1,
            Hp = 60,
            Drop = 1,
        }
    end,
}

function CfgC_Resources.Get_dCfgResource(id)
    local data = CfgC_Resources.dCfgResource[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgResource[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgC_Resources.dCfgResource[id] = data
    return data
end

function CfgC_Resources.Get_CfgResourceByIndex(index)
    if index < 0 or index >= #CfgC_Resources.allCfgResources then
        return nil
    end
    return CfgC_Resources.Get_dCfgResource(CfgC_Resources.allCfgResources[index + 1])
end

return CfgC_Resources
