-- ============================================================================
-- CfgC_Colors (client)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: Colors.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgC_Colors = {}

CfgC_Colors.SNOW1 = { 155, 160, 168 } -- 脏灰雪
CfgC_Colors.SNOW2 = { 130, 138, 148 } -- 深灰雪纹
CfgC_Colors.SNOW3 = { 170, 175, 182 } -- 浅灰
CfgC_Colors.SNOW_DARK = { 105, 112, 125 } -- 阴影区
CfgC_Colors.PATH = { 85, 78, 68 } -- 暗褐冻土
CfgC_Colors.PATH_LIGHT = { 100, 92, 80 } -- 碎石亮面
CfgC_Colors.PATH_DARK = { 60, 55, 45 } -- 泥坑暗部
CfgC_Colors.PATH_EDGE = { 120, 125, 135 } -- 路缘过渡
CfgC_Colors.TRAIN_BODY = { 52, 55, 50 } -- 暗铁灰车身
CfgC_Colors.TRAIN_DARK = { 35, 38, 32 } -- 深暗面
CfgC_Colors.TRAIN_LIGHT = { 72, 78, 68 } -- 微弱高光
CfgC_Colors.TRAIN_ROOF = { 40, 42, 38 } -- 车顶
CfgC_Colors.TRAIN_METAL = { 65, 68, 62 } -- 金属件
CfgC_Colors.TRAIN_WINDOW = { 75, 105, 130 } -- 脏窗玻璃
CfgC_Colors.TRAIN_WINDOW2 = { 55, 80, 105 } -- 深色窗
CfgC_Colors.TRAIN_STRIPE = { 140, 35, 25 } -- 暗血红装饰
CfgC_Colors.TRAIN_STRIPE2 = { 110, 25, 18 } -- 深红锈
CfgC_Colors.TRAIN_BRASS = { 145, 120, 55 } -- 氧化铜
CfgC_Colors.TRAIN_BRASS2 = { 170, 145, 70 } -- 铜亮面
CfgC_Colors.TRAIN_BRASS3 = { 110, 90, 40 } -- 铜暗面
CfgC_Colors.TRAIN_SMOKE = { 38, 35, 30 } -- 烟囱黑
CfgC_Colors.TRAIN_SMOKE2 = { 25, 22, 18 } -- 烟囱暗
CfgC_Colors.TRAIN_RIVET = { 80, 85, 75 } -- 锈铆钉
CfgC_Colors.TRAIN_FRAME = { 30, 32, 28 } -- 暗轮廓
CfgC_Colors.TRAIN_PLATE = { 120, 105, 55 } -- 锈铭牌
CfgC_Colors.TRAIN_CAB_BG = { 45, 48, 42 } -- 驾驶室
CfgC_Colors.TRAIN_PIPE = { 95, 90, 80 } -- 锈管道
CfgC_Colors.RAIL_COLOR = { 75, 78, 85 } -- 暗铁轨
CfgC_Colors.RAIL_LIGHT = { 100, 105, 115 } -- 磨亮面
CfgC_Colors.SLEEPER_COLOR = { 70, 60, 42 } -- 腐朽枕木
CfgC_Colors.SLEEPER_DARK = { 48, 40, 28 } -- 枕木暗面
CfgC_Colors.BALLAST_COLOR = { 80, 75, 65 } -- 暗碎石
CfgC_Colors.SUBMIT_BG = { 55, 58, 65, 220 } -- 提交区背景
CfgC_Colors.SUBMIT_BORDER = { 85, 90, 100 } -- 提交区边框
CfgC_Colors.SUBMIT_FULL = { 50, 130, 80 } -- 已满暗绿
CfgC_Colors.HUD_BG = { 18, 20, 28, 240 } -- HUD背景
CfgC_Colors.HUD_BORDER = { 40, 45, 58 } -- HUD边框
CfgC_Colors.HUD_TEXT = { 175, 180, 190 } -- HUD文字
CfgC_Colors.TRUNK = { 55, 45, 35 } -- 黑褐树干
CfgC_Colors.TRUNK_DARK = { 35, 28, 20 } -- 腐烂暗部
CfgC_Colors.TREE_SNOW = { 140, 148, 160 } -- 灰雪
CfgC_Colors.TREE_BARE = { 65, 52, 40 } -- 枯枝
CfgC_Colors.TREE_DARK = { 45, 38, 28 } -- 暗枝
CfgC_Colors.SNOWDRIFT1 = { 148, 155, 165 } -- 脏雪堆
CfgC_Colors.SNOWDRIFT2 = { 120, 128, 140 } -- 深灰雪
CfgC_Colors.RUIN_COLOR = { 68, 62, 55 } -- 废墟残骸
CfgC_Colors.WOOD_COLOR = { 110, 78, 40 } -- 暗木色
CfgC_Colors.STONE_COLOR = { 95, 95, 105 } -- 暗岩灰
CfgC_Colors.ORE_COLOR = { 65, 120, 170 } -- 深蓝矿脉
CfgC_Colors.BUSH_COLOR = { 60, 100, 50 } -- 深绿灌木
CfgC_Colors.PEBBLE_COLOR = { 130, 125, 115 } -- 浅灰碎石
CfgC_Colors.GOLD_COLOR = { 200, 165, 40 } -- 暗金
CfgC_Colors.ZOMBIE_SKIN = { 85, 110, 72 } -- 腐肉绿
CfgC_Colors.ZOMBIE_DARK = { 50, 65, 38 } -- 深腐色
CfgC_Colors.ZOMBIE_EYE = { 200, 35, 20 } -- 血红眼
CfgC_Colors.ZOMBIE_CLOTH = { 55, 48, 42 } -- 破烂深色
CfgC_Colors.PLAYER_COAT = { 125, 55, 35 } -- 暗红破旧大衣
CfgC_Colors.PLAYER_SKIN = { 185, 155, 130 } -- 偏暗肤色
CfgC_Colors.PLAYER_PANTS = { 48, 50, 58 } -- 深灰裤
CfgC_Colors.PLAYER_BOOT = { 38, 35, 28 } -- 泥靴
CfgC_Colors.PLAYER_HAT = { 105, 42, 28 } -- 暗红帽
CfgC_Colors.PLAYER_SCARF = { 145, 125, 40 } -- 脏黄围巾
CfgC_Colors.TEXT_WHITE = { 220, 225, 230 } -- 偏灰白
CfgC_Colors.TEXT_DARK = { 15, 18, 25 } -- 深色
CfgC_Colors.TEXT_DIM = { 100, 108, 120 } -- 暗灰
CfgC_Colors.TEXT_RED = { 190, 50, 35 } -- 暗血红
CfgC_Colors.CARD_BG = { 28, 32, 42 } -- 卡片背景
CfgC_Colors.CARD_BORDER = { 55, 60, 75 } -- 卡片边框
CfgC_Colors.CARD_GLOW = { 70, 140, 200 } -- 卡片发光
CfgC_Colors.BLOOD_COLOR = { 180, 30, 20 } -- 飙血颜色
CfgC_Colors.BG_DARK = { 18, 20, 28, 255 } -- 最深背景
CfgC_Colors.BG_PANEL = { 28, 32, 42, 255 } -- 面板背景
CfgC_Colors.BG_CARD = { 38, 42, 55, 255 } -- 卡片背景
CfgC_Colors.BG_INPUT = { 22, 25, 35, 255 } -- 输入框背景
CfgC_Colors.BAR_BG = { 14, 16, 22, 245 } -- 顶/底栏背景
CfgC_Colors.BAR_BORDER = { 45, 50, 65, 255 } -- 栏边框
CfgC_Colors.TAB_ACTIVE = { 70, 140, 200, 255 } -- 激活Tab颜色
CfgC_Colors.TAB_INACTIVE = { 100, 108, 120, 255 } -- 未激活Tab
CfgC_Colors.TAB_BG = { 22, 25, 35, 240 } -- Tab背景
CfgC_Colors.BTN_PRIMARY = { 55, 130, 85, 255 } -- 主按钮暗绿
CfgC_Colors.BTN_SECONDARY = { 50, 55, 70, 255 } -- 次按钮
CfgC_Colors.BTN_DANGER = { 160, 45, 35, 255 } -- 危险按钮
CfgC_Colors.BTN_GOLD = { 180, 145, 40, 255 } -- 金色按钮
CfgC_Colors.META_TEXT_WHITE = { 220, 225, 230, 255 } -- 白色文字
CfgC_Colors.META_TEXT_GRAY = { 130, 138, 150, 255 } -- 灰色文字
CfgC_Colors.META_TEXT_DIM = { 80, 85, 95, 255 } -- 暗灰文字
CfgC_Colors.META_TEXT_GOLD = { 220, 185, 50, 255 } -- 金色文字
CfgC_Colors.META_TEXT_GREEN = { 65, 180, 90, 255 } -- 绿色文字
CfgC_Colors.META_TEXT_RED = { 200, 55, 40, 255 } -- 红色文字
CfgC_Colors.DIVIDER = { 40, 45, 58, 255 } -- 分割线

return CfgC_Colors
