-- ============================================================================
-- CfgC_Shop (client)
-- Auto-generated by @ospec_config-skill/scripts/excel_to_lua_modules.py
-- Source workbook: Shop.xlsx
-- Do not edit manually.
-- ============================================================================

local CfgC_Shop = {}

CfgC_Shop.NAME = "末日抽卡" -- 抽卡系统名称
CfgC_Shop.DESC = "消耗钻石抽取装备碎片" -- 抽卡描述
CfgC_Shop.COST_SINGLE = 100 -- 单抽费用
CfgC_Shop.COST_TEN = 900 -- 十连费用

CfgC_Shop.dCfgShopDaily = {}
CfgC_Shop.allCfgShopDailys = {
    1,
    2,
    3,
    4,
}
local _createCfgShopDaily = {
    [1] = function()
        return {
            Id = 1,
            Key = "daily_gold",
            Name = "金币礼包",
            Desc = "获得500金币",
            Price = 50,
            Currency = "diamond",
            Icon = "image/hud_gold_coin.png",
        }
    end,
    [2] = function()
        return {
            Id = 2,
            Key = "daily_wood",
            Name = "木材补给",
            Desc = "获得20木材",
            Price = 30,
            Currency = "diamond",
            Icon = "image/meta_icon_wood_20260421063709.png",
        }
    end,
    [3] = function()
        return {
            Id = 3,
            Key = "daily_stone",
            Name = "石材补给",
            Desc = "获得15石材",
            Price = 30,
            Currency = "diamond",
            Icon = "image/meta_icon_stone_20260421063705.png",
        }
    end,
    [4] = function()
        return {
            Id = 4,
            Key = "daily_chest",
            Name = "银色宝箱",
            Desc = "随机稀有装备×1",
            Price = 100,
            Currency = "diamond",
            Icon = "image/chest_silver_20260421064733.png",
        }
    end,
}

function CfgC_Shop.Get_dCfgShopDaily(id)
    local data = CfgC_Shop.dCfgShopDaily[id]
    if data ~= nil then
        return data
    end
    local creator = _createCfgShopDaily[id]
    if creator == nil then
        return nil
    end
    data = creator()
    CfgC_Shop.dCfgShopDaily[id] = data
    return data
end

function CfgC_Shop.Get_CfgShopDailyByIndex(index)
    if index < 0 or index >= #CfgC_Shop.allCfgShopDailys then
        return nil
    end
    return CfgC_Shop.Get_dCfgShopDaily(CfgC_Shop.allCfgShopDailys[index + 1])
end

return CfgC_Shop
